### PR TITLE
Remove `::{{closure}}` in more cases from function names

### PR DESCRIPTION
**Pull request by Hoodad**
### Checklist

* [x] I have read the [Contributor Guide](../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This removes all `::{{closure}}` from the suffix of a function name when cleaning the name. Previously this was limited to 2. 

This is noticeable with the changes made in #225 where the `main function` being labeled as `main::{{closure}}`

### Before
image

### After 
Screenshot 2024-08-05 131903

### CODE REVIEW

**Review by emilk — APPROVED** [review]

**Comment by Hoodad** [comment]
I haven't tested how this looks with more closure examples. But can try it out more.

Regarding the function to have something come up as a closure, personally I would rather see a name then a generic closure tag, though I cannot say that I'm a heavy user of profiling scopes 🙈

**Comment by Hoodad** [comment]
I did sanity check the code and it does behave as advertised, removing all mentions of `::{{closure}}`. 

If you then profile a closure and use `puffin::profile_function()` it will be labelled the same as the function where the closure is being called. If a name is required I would suggest opting for `profile::profile_scope()` instead as then you can give it a name.

**Comment by TimonPost** [comment]
Makes sense to me for ppl to use scopes in this case.

**Comment by emilk** [comment]
We may wanna add that to the docstring of `profile_function`, that it is only meant for the outermost scope of a `fn` function, and NOT for lambdas.

**Comment by Hoodad** [comment]
Yeah make sense, I did update the documentation now. 

Though I realize now with the change in documentation the eframe example does not adhere to this standard as it uses the `profile_function` in the `eframe::run_simple_native`. That said I think its fine as the output will be `eframe::main` which is expected. Just a tiny bit inconsistent with the documentation 🙈

**Review by emilk — APPROVED** [review]

**Pull request merged**
