### PR TITLE
Fix broken flamegraph interaction with egui 0.27.1

### PR DESCRIPTION
**Pull request by abey79**
### Checklist

* [x] I have read the [Contributor Guide](../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This PR cancels the revert (#208) of egui 0.27.1 update (#201) and fix the flamegraph interaction bug it introduced whenever the flamegraph's scroll area was active.

### Related Issues

* Closes https://github.com/EmbarkStudios/puffin/pull/207
* Closes https://github.com/EmbarkStudios/puffin/issues/205

### CODE REVIEW

**Comment by tosti007** [comment]
I've tested this on Windows and MacOs, in neither case the issues described in #205 are solved.

**Review by emilk — APPROVED** [review]
Great!

**Comment by emilk** [comment]
I guess I misread the comment… well, this fixed all the problems I could find

**Comment by tosti007** [comment]
> I guess I misread the comment… well, this fixed all the problems I could find

My bad, I should've phrased it better. I'll see what I can find!

**Comment by Hoodad** [comment]
I don't know how this was tested but I can only echo what @tosti007 said that the flamegraph selection still has issues for me when scrolling even after this was merged. I think I have located the source of the issue and tried to describe relevant parts here #219

**Pull request merged**
