### PR TITLE
Remove `imgui` support in favor of `egui`

### PR DESCRIPTION
**Pull request by repi**
Most Rust project use the native `egui` instead, including us so we don't want to maintain `imgui` support that we don't use.

Significantly reduces the dependency tree for development as we were pulling in old `winit` and almost deprecated `glium` renderers for it (`egui` uses `wgpu`).

cargo-vet stats (the exempted number is the most important):
- Before: `Vetting Succeeded (168 fully audited, 10 partially audited, 173 exempted)`
- After: `Vetting Succeeded (151 fully audited, 10 partially audited, 133 exempted)`

Resolves: #139
Resolves: #134

### CODE REVIEW

**Comment by TimonPost** [comment]
Shall we open an issue on imgui-rs to see if they want ownership?

**Comment by repi** [comment]
nah don't think so, they do not own any applications built on imgui, just the imgui bindings themselves

**Comment by TimonPost** [comment]
Probably! Should we bother creating new repo with last code and [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) it?

**Comment by repi** [comment]
I think publishing a last release of the crate before this is merged, and changing the maintenance status in `Cargo.toml` to unsupported (think the `as-is` badge status listed here https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section). then we have a release tag or commit hash for that which can be referenced for anyone wanting to get the last version. so no need to create a separate repo

**Review by TimonPost — APPROVED** [review]
Lets do it like that then :)

**Pull request merged**
